version: '3'

services:   
  repl:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7888:7888"
      - "3449:3449"
    volumes:
      - .:/usr/src/app:Z
    user: "jenkins:shared"
    command: lein repl :headless :host 0.0.0.0 :port 7888

  reactnative:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    # user: "jenkins:shared"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app:Z
      - ~/.gradle:/usr/src/app/android/gradle_deps:Z
    command: react-native start

    # test:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-Alternative
    # user: "jenkins:shared"
    # working_dir: /usr/src/app
    # volumes:
    #   - .:/usr/src/app:Z
    #   - /usr/src/app/node_modules
    # command:
    #     - tail 
    #     - -f 
    #     - /dev/null 