FROM clojure:lein

RUN wget -qO- https://deb.nodesource.com/setup_4.x | bash - \
    && apt-get install -y nodejs
ENV PATH $PATH:node_modules/.bin

WORKDIR /usr/src
COPY package*.json .

RUN npm install -g react-native-cli re-natal
RUN npm install && npm i invariant
