test:
  build: Dockerfile-Alternative
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
  command:
      - tail 
      - -f 
      - /dev/null 

# services:
#   repl:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "7888:7888"
#       - "3449:3449"
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     # user: root
#     # command: lein repl :headless :host 0.0.0.0 :port 7888
#     # command:
#     #   - tail 
#     #   - -f 
#     #   - /dev/null 
#       # - | 
#       #   ls
#         # lein repl :headless :host 0.0.0.0 :port 7888
#     # links:
#       # - reactnative


  # reactnative:
  #   build: .
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - .:/usr/src/app
  #     - ~/.gradle:/usr/src/app/android/gradle_deps
  #     # - ~/.android:/root/.android
  #     # - ~/.m2:/root/.m2
  #     # - /dev/bus/usb:/dev/bus/usb
  #   command: react-native start
  #   # privileged: true
  #   # environment:
  #   #   TERM: dumb
